import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import SmallScreenMenuProvider from "@/contexts/smallScreenMenuContext";
import SmallScreenMenu from "@/components/uiComponents/smallScreenMenu";
import TopBanner from "@/components/topBanner";
import Header from "@/components/header";
import HeaderMenu from "@/components/headerMenu";
import Footer from "@/components/footer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SmallScreenMenuProvider>
            <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col justify-start items-center`}
            >
            <SmallScreenMenu/>
            <TopBanner/>
            <hr className="border-dashed w-full hidden md:block"/>
            <Header/>
            <HeaderMenu/>
            {children}
            <div className="lg:my-5"></div>
            <Footer/>
            </body>
            </html>
        </SmallScreenMenuProvider>
    );
}
